workflows:
  react-native-ios:
    name: Lama_v3 iOS
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      node: 16.18.1
      npm: latest
      flutter: stable
      xcode: latest
      groups:
        - group_name
      vars:
        BUNDLE_ID: "com.tryLama.Lama"
        XCODE_WORKSPACE: "HelloWorld.xcworkspace" # <-- Put the name of your Xcode workspace here
        XCODE_SCHEME: "HelloWorld" # <-- Put the name of your Xcode scheme here
        APP_ID: 1527028000
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.tryLama.Lama
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Install Expo CLI and eject
        script: |
          yarn install
          yarn global add expo-cli
          expo eject
      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - hello@grantcgarland.com
      scripts:
        - echo 'Post-publish script'
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - App Store Connect Users
          - Internal testers

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
